# Generated by Django 3.2.4 on 2021-06-14 14:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('podName', models.CharField(max_length=100)),
                ('userName', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('bookingTime', models.DateTimeField()),
                ('create', models.DateTimeField(default=django.utils.timezone.now)),
                ('update', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
